[package]
name = "disrupt-bigfile"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
byteorder = "1.5.0"
clap = { version = "4.5.48", features = ["derive"] }
fnv1 = "1.0.0"
indicatif = "0.18.3"
lzxd = "0.2.6"
rkyv = "0.8.15"
thiserror = "2.0.18"
walkdir = "2.5.0"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"

[build-dependencies]
fnv1 = "1.0.0"
rkyv = "0.8.15"
