[package]
name = "disrupt-bigfile"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.103", optional = true }
byteorder = "1.5.0"
clap = { version = "4.5.48", features = ["derive"], optional = true }
fnv1 = "1.0.0"
indicatif = { version = "0.18.3", optional = true }
lzxd = "0.2.6"
rkyv = "0.8.15"
thiserror = "2.0.18"
walkdir = { version = "2.5.0", optional = true }

[build-dependencies]
anyhow = "1.0.103"
fnv1 = "1.0.0"
rkyv = "0.8.15"
disrupt-bigfile-filelists-wd1 = { path = "../disrupt-bigfile-filelists-wd1", optional = true }
disrupt-bigfile-filelists-wd2 = { path = "../disrupt-bigfile-filelists-wd2", optional = true }
disrupt-bigfile-filelists-wdl = { path = "../disrupt-bigfile-filelists-wdl", optional = true }

[features]
cli = ["dep:anyhow", "dep:clap", "dep:indicatif", "dep:walkdir"]
wd1 = ["dep:disrupt-bigfile-filelists-wd1"]
wd2 = ["dep:disrupt-bigfile-filelists-wd2"]
wdl = ["dep:disrupt-bigfile-filelists-wdl"]
default = ["wd1", "wd2", "wdl"]

[[bin]]
name = "disrupt-bigfile"
required-features = ["cli"]

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"
